### PR TITLE
add HOOK_POST_CREATION

### PR DESCRIPTION
**Pull request by M-M-M-M**
Add a hook after creation of certificate in order to be able to clean challenge on remote servers and to upload created certs.

To replace pull request #22 with a cleaner commits from last master.

### CODE REVIEW

**Comment by hoedlmoser** [comment]
@M-M-M-M I'm not sure what your purpose for this post script is, but in my case I would distribute the certs and keys to all my VMs. so, better to have only certs directory and domain name (because filenames are well known) to be able to create kind of directory structure also on the destination host?

**Comment by M-M-M-M** [comment]
@hoedlmoser  I am using this post script in order to build a chain pem file with intermediate certificates in order to provide it to Haproxy, to deploy this file to all servers by scp, then to send a reload configuration to all Haproxy servers in order to take in account new certificates. Goal is to automate the process on renewal as much as possible.  Croning letsencrypt.sh and that's all. 

Haproxy and Apache need intermediate certificates to avoid warning message on SSL check.

**Comment by M-M-M-M** [comment]
@hoedlmoser And as I am using the HOOK_CHALLENGE to copy by scp the .acme-challenges files I would like to delete it from remote server once certificates have been created.

**Comment by germeier** [comment]
FYI: Your code does not call the hook if there is a problem generating the new cert!

**Comment by M-M-M-M** [comment]
@germeier You are right. I have create pull request #25 to take in account your comment.

I have added the hook before the exit and added a status parameter to the hook program about the valid/invalid challenge result.

**Comment by silvio** [comment]
please close #22 and this one in favour for #25

**Pull request closed without merging**
