### PR TITLE
Use of 'grep -o' doesn't work on SunOS (fixes #164)

### LINKED ISSUE #164: Use of `grep -o` doesn't work on SunOS
The `-o` flag isn't supported on either `/usr/bin/grep` or `/usr/xpg4/bin/grep`, and gnu grep is not always available.

### PR DESCRIPTION
**Pull request by bahamat**
Fixes #164.

Change some calls from `grep -o` to `sed`. These changes have been tested on SmartOS in the GZ, SmartOS in a zone with pkgsrc, Mac OS X and Linux (Ubuntu 14.04).

This allows `letsencrypt.sh` to be used from the global zone on SmartOS without requiring bootstrapping pkgsrc or installing additional tools.

### CODE REVIEW

**Comment by bahamat** [comment]
Rebased from master, and it looks like the CI build failed due to a transient error (502 response from web server on the challenge check).

Running `test.sh` in a test container of my own passes all checks.

```
root@1abbc92ab4a9:/letsencrypt.sh# git reset --hard; ./test.sh
HEAD is now at 014e116 Use of 'grep -o' doesn't work on SunOS (fixes #164)
--2016-03-11 01:03:46--  https://dl.ngrok.com/ngrok_2.0.19_linux_amd64.zip
Resolving dl.ngrok.com (dl.ngrok.com)... 45.33.127.226
Connecting to dl.ngrok.com (dl.ngrok.com)|45.33.127.226|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4021793 (3.8M) [application/zip]
Saving to: 'ngrok.zip'

100%[========================================================================================================================================>] 4,021,793   12.5MB/s   in 0.3s   

2016-03-11 01:03:47 (12.5 MB/s) - 'ngrok.zip' saved [4021793/4021793]

Archive:  ngrok.zip
  inflating: ngrok                   

Checking if help command is working... 
 + Checking if log contains 'Default command: help'... [PASS]
 + Checking if log contains '--help (-h)'... [PASS]
 + Checking if log contains '--domain (-d) domain.tld'... [PASS]
 + Checking if errorlog is empty... [PASS]

First run in cron mode, checking if private key is generated and registered 
 + Checking if log contains 'Registering account key'... [PASS]
 + Checking if file 'private_key.pem' exists... [PASS]
 + Checking if errorlog is empty... [PASS]

Try signing using temporary config location and with domain as command line parameter 
 + Checking if log doesn't contain 'Checking domain name(s) of existing cert'... [PASS]
 + Checking if log contains 'Generating private key'... [PASS]
 + Checking if log contains 'Requesting challenge for d9b5f6db.ngrok.io'... [PASS]
 + Checking if log contains 'Requesting challenge for a13d2b94.ngrok.io'... [PASS]
 + Checking if log contains 'Challenge is valid!'... [PASS]
 + Checking if log contains 'Creating fullchain.pem'... [PASS]
 + Checking if log contains 'Done!'... [PASS]
 + Checking if errorlog is empty... [PASS]

Run in cron mode again, this time adding third domain, should force renewal. 
 + Checking if log contains 'Domain name(s) are not matching!'... [PASS]
 + Checking if log contains 'Forcing renew.'... [PASS]
 + Checking if log contains 'Requesting challenge for d9b5f6db.ngrok.io'... [PASS]
 + Checking if log contains 'Requesting challenge for a13d2b94.ngrok.io'... [PASS]
 + Checking if log contains 'Requesting challenge for 18154e1a.ngrok.io'... [PASS]
 + Checking if log contains 'Challenge is valid!'... [PASS]
 + Checking if log contains 'Creating fullchain.pem'... [PASS]
 + Checking if log contains 'Done!'... [PASS]
 + Checking if errorlog is empty... [PASS]

Run in cron mode again, this time with domain in domains.txt, should find non-expiring certificate 
 + Checking if log contains 'Checking domain name(s) of existing cert... unchanged.'... [PASS]
 + Checking if log contains 'Skipping!'... [PASS]
 + Checking if errorlog is empty... [PASS]

Run in cron mode one last time, with domain in domains.txt and force-resign 
 + Checking if log contains 'Checking domain name(s) of existing cert... unchanged.'... [PASS]
 + Checking if log contains 'Ignoring because renew was forced!'... [PASS]
 + Checking if log doesn't contain 'Generating private key'... [PASS]
 + Checking if log contains 'Requesting challenge for d9b5f6db.ngrok.io'... [PASS]
 + Checking if log contains 'Requesting challenge for a13d2b94.ngrok.io'... [PASS]
 + Checking if log contains 'Requesting challenge for 18154e1a.ngrok.io'... [PASS]
 + Checking if log contains 'Challenge is valid!'... [PASS]
 + Checking if log contains 'Creating fullchain.pem'... [PASS]
 + Checking if log contains 'Done!'... [PASS]
 + Checking if errorlog is empty... [PASS]

Running signcsr command 
 + Checking if log contains 'BEGIN CERTIFICATE'... [PASS]
 + Checking if log contains 'END CERTIFICATE'... [PASS]
 + Checking if log doesn't contain 'ERROR'... [PASS]

Run in cron mode again, to check if renewal works 
 + Checking if log contains 'Checking domain name(s) of existing cert... unchanged.'... [PASS]
 + Checking if log contains 'Renewing!'... [PASS]
 + Checking if errorlog is empty... [PASS]

Verifying certificate... 
 + Verifying certificate on its own... [PASS]
 + Checking if log contains 'CN=d9b5f6db.ngrok.io'... [PASS]
 + Checking if log contains 'a13d2b94.ngrok.io'... [PASS]
 + Verifying file with full chain... [PASS]
 + Verifying certificate against CA certificate... [PASS]
 + Checking if errorlog is empty... [PASS]

Revoking certificate... 
 + Checking if log contains 'Revoking certs/d9b5f6db.ngrok.io/cert-1457658322.pem'... [PASS]
 + Checking if log contains 'Done.'... [PASS]
 + Checking if file 'certs/d9b5f6db.ngrok.io/cert-1457658322.pem-revoked' exists... [PASS]
 + Checking if errorlog is empty... [PASS]

Cleaning up certificates 
 + Checking if log contains 'Moving unused file to archive directory: d9b5f6db.ngrok.io/cert-'... [PASS]
 + Checking if log contains 'Moving unused file to archive directory: d9b5f6db.ngrok.io/chain-'... [PASS]
 + Checking if log contains 'Moving unused file to archive directory: d9b5f6db.ngrok.io/fullchain-'... [PASS]
 + Checking if errorlog is empty... [PASS]
```

**Comment by lukas2511** [comment]
I reran the tests and everything looks fine. Currently don't really have the time to look over bigger changes, so that'll have to wait until next week, but thanks for bringing this up!

**Comment by lukas2511** [comment]
Hey, I just had a look at your changes.

The only issue I see is that your sed based replacements return the whole input when there is no match:

```
Ξ (serenity) ~ → echo '"bla":"test","challenges":[]' | sed 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/'
"challenges":[]
Ξ (serenity) ~ → echo '"bla":"test","nochallengesforyou":[]' | sed 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/'
"bla":"test","nochallengesforyou":[]
Ξ (serenity) ~ → echo '"foo":"bar"' | sed 's/.*"foo": *"\([^"]*\)".*/\1/'
bar
Ξ (serenity) ~ → echo '"nofoo":"bar"' | sed 's/.*"foo": *"\([^"]*\)".*/\1/'
"nofoo":"bar"
```

If you can fix this issue I don't see any problem with merging it.

**Comment by bahamat** [comment]
Ah, good catch. I'm pretty sure I can fix that. I'll have an update later today.

**Comment by bahamat** [comment]
Ok, I've fixed those by using `sed -n`. Using your examples:

```
bash-3.2$ echo '"bla":"test","challenges":[]' | sed -n 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/'
bash-3.2$ echo '"bla":"test","nochallengesforyou":[]' | sed -n 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/'
bash-3.2$ echo '"foo":"bar"' | sed -n 's/.*"foo": *"\([^"]*\)".*/\1/'
bash-3.2$ echo '"nofoo":"bar"' | sed -n 's/.*"foo": *"\([^"]*\)".*/\1/'
bash-3.2$ 
```

I get the same results on Linux, Mac OS X and SmartOS.

And I think the CI tests failure, is again a transient error. The test suite passes when using my test container (as above).

**Comment by lukas2511** [comment]
@bahamat but now it doesn't return anything, even on those were it should return something. that's why the tests are failing.

`"foo":"bar"` should return `bar` 
`"nofoo":"bar"` should be empty

but both are empty, which is understandable since '-n' on sed disables the default print command

adding a `p` at the end seems to work:

```
Ξ (serenity) ~ → echo '"bla":"test","challenges":[]' | sed -n 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/p'
"challenges":[]
Ξ (serenity) ~ → echo '"bla":"test","nochallengesforyou":[]' | sed -n 's/.*\("challenges":[^\[]*\[[^]]*]\).*/\1/p'
Ξ (serenity) ~ → echo '"foo":"bar"' | sed -n 's/.*"foo": *"\([^"]*\)".*/\1/p'
bar
Ξ (serenity) ~ → echo '"nofoo":"bar"' | sed -n 's/.*"foo": *"\([^"]*\)".*/\1/p'
```

**Comment by bahamat** [comment]
Yep, you're right, I did forget that. Fixed up now.

**Pull request merged**
