### PR TITLE
pass timestamp and key_algo to deploy hook

### PR DESCRIPTION
**Pull request by bax-**

### CODE REVIEW

**Comment by bax-** [comment]
see https://github.com/lukas2511/letsencrypt.sh/issues/129

**Comment by lukas2511** [comment]
Actually I think we should reduce this to just the timestamp argument and export KEY_ALGO like some other config values are exported:

```
# Export some environment variables to be used in hook script
export WELLKNOWN BASEDIR CONFIG
```

We may want to move that new export to the actual signing loop for future-compatiblity with per-cert configurations.

**Comment by lukas2511** [comment]
timestamp is now a parameter of the `deploy_cert`-hook and KEY_ALGO is exported as environment variable

**Comment by clydeclements** [comment]
Just one minor comment: I think you should update the `hook.sh.example` file inline with the commit above to show that `deploy_cert` now takes an additional timestamp argument. I just got bitten by this, writing a hook script with `deploy_cert` expecting 5 arguments, when 6 was required. Great software though!

**Comment by lukas2511** [comment]
@clydeclements done, thanks.

**Pull request closed without merging**
