### PR TITLE
Adding the ability to build a Debian package

### PR DESCRIPTION
**Pull request by ipartola**
For Debian-based systems, it would be really nice to have a .deb package that's installable in a standard manner. This PR includes the files necessary to build a .deb package. Note that a new file has been added: docs/examples/config.sh.debian. This config file includes defaults suitable for the Debian filesystem layout. Otherwise, it mirrors what is used by the vanilla docs/examples/config.sh.example.

To try this out, run `debuild -us -uc` on a Debian or Ubuntu box, then `dpkg -i ../letsencryptsh_0.1.1_all.deb` to install it.

If/when this PR is accepted, we should find a place to host the build package as an APT repository. I can take care of it if @lukas2511 does not have experience with this. We'd also need to update the README.md file with Debian/Ubuntu-specific instructions.

### CODE REVIEW

**Comment by lukas2511** [comment]
I'm sorry but I don't think this has a place in this repository. 
If i'd add Debian package-build files i'd feel obliged to also add stuff for other distributions and this would really clutter this repository.

Other people packaged letsencrypt.sh outside of this repository (there are at least ports for freebsd and a package for suse/centos/fedora), so you might be able to do the same for a Debian package, I guess there are mechanisms for doing this as I doubt every piece of software in the Debian repositories has added this clutter to their main repository.

**Comment by lukas2511** [comment]
related to #96

**Comment by seefood** [comment]
@ipartola It's still a good initiative though. May I suggest a PPA on Launchpad? I'll be happy to subscribe.

**Comment by ipartola** [comment]
I have no problem with hosting it myself. I just need some way to get notified of new releases. I will probably not host it on LaunchPad, since their build mechanism is annoying, but I have a pretty simple way of doing it on S3. I'll also look into getting this packaged for Debian directly, though I am not a Debian maintainer so I cannot say how easy that would be.

**Comment by lukas2511** [comment]
@ipartola if you have a service that works with a github webhook i would add that

**Comment by seefood** [comment]
Just a cronjob that runs git pull every 6-12 hours, and if there's new stuff, a git hook will build and upload. It's as simple as that, done it before. I wish github would allow one to be alerted of updates to a branch, Or have I missed this?

**Comment by lukas2511** [comment]
@seefood 
screen shot 2016-04-01 at 15 09 56

**Comment by ipartola** [comment]
Hmm. Some automated testing would be needed to ensure it doesn't break. Not just testing of the script itself, but that things like config files didn't change in a way that would break the Debian installation, etc. As you can see in my pull request, I had to add a config.sh.debian with defaults suitable for a Debian filesystem layout. I could certainly maintain my own set of patches that get applied on top of the upstream release, but I'd need to write additional tests to be able to do so automatically.

I will see what I can do. Another approach is to get letsencrypt.sh into the official Debian repositories. That would be my preferred method, as there are currently no other decent LE clients that come with Debian/Ubuntu, and this is a critical piece of infrastructure that should be there. I'll explore this option as well.

**Comment by lukas2511** [comment]
@ipartola if you want to write better tests for letsencrypt.sh feel free to do so. currently there are only a few tests which are basically just enough to show if something went horribly wrong in a commit.

**Comment by bootc** [comment]
Has there been any progress on this? I'm a Debian Developer and would gladly work with someone to get letsencrypt.sh into Debian.

I see someone has already started work as part of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812174 - is this related to what's going on here?

Thanks,
Chris

**Comment by ipartola** [comment]
@bootc I'd love to work with you on this. I started looking into how to get a sponsor for this. That bug report is not related, I did the packaging on my own as a native package so far. Seems like I should re-package it as a regular package with external sources and add my patches (a Makefile and a separate config.sh that is Debian-specific). Personally, I'd love to use this as an opportunity to start getting various things packaged for Debian.

What is the best way to proceed? Discuss on this ticket? Take the discussion to debian-metors? Email you privately?

**Comment by lukas2511** [comment]
btw. this already is released as a package in freebsd and now in opensuse

**Comment by ymc-dabe** [comment]
FWIW: letsencrypt.sh is [packaged in Debian](https://packages.debian.org/letsencrypt.sh). It is packaged using `git buildpackage` and it's packaging git repository can be found at: https://anonscm.debian.org/git/letsencrypt/letsencrypt.sh.git/

**Pull request closed without merging**
