### PR TITLE
Add detail as to how dns-01 hook works

### PR DESCRIPTION
**Pull request by davidearl**
I just got this working with my provider's DNS API, but I had to inspect the script as to how to do it, so I thought some detail might be useful in the readme

### CODE REVIEW

**Comment by davidearl** [comment]
Yes, I know. That's why I was doing it. It all worked really nicely with my provider's DNS API: https://www.mythic-beasts.com/support/api/primary 

remarkably easy

FWIW, here's my hook script (for deploy_challenge only)

        #!/bin/bash
        if [[ "$1" = "deploy_challenge" ]]; then
            echo " ++ setting DNS for $2 to $4"
            while read DNSDOMAIN DNSAPIPASSWORD; do
                if [[ "$2" == *$DNSDOMAIN ]] ; then
                    ZONE=$(echo $2 | sed -e "s/\\.$DNSDOMAIN\$//")
                    curl -d "domain=$DNSDOMAIN" -d "password=$DNSAPIPASSWORD" -d "command=REPLACE _acme-challenge.$ZONE 300 TXT $4" "https://dnsapi.mythic-beasts.com/"
                    echo sleeping 60 seconds for change to take effect..
                    sleep 60
                    break;
                fi
            done < ./dnsapi.config.txt
        else
            echo "hook said..."
            echo "$1 $2 $3 $4"
        fi

**Comment by lukas2511** [comment]
I'll merge this now, but I think hooks should actually be explained in their own readme-section. This has to be worked on.

**Comment by jantore** [comment]
I think that a hook.sh.example file could also be a good way to get users up to speed quickly. I'm thinking something along the lines of this:
```bash
#!/bin/bash

function deploy_challenge {
    local ALTNAME="${1}" TOKEN_FILENAME="${2}" TOKEN_CONTENT="${3}"

    # pass
}

function clean_challenge {
    local ALTNAME="${1}" TOKEN_FILENAME="${2}" TOKEN_CONTENT="${3}"

    # pass
}

function deploy_cert {
    local DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" CHAINFILE="${4}"

    # pass
}

HANDLER=$1; shift; $HANDLER $@
```
I'll send a PR if you want.

**Comment by lukas2511** [comment]
Yea maybe also add some comments explaining a bit when a hook gets called, that would be great.

**Pull request merged**
