### PR TITLE
Make letsencrypt.sh zsh-compatible

### PR DESCRIPTION
**Pull request by Sp1l**
- Allow zsh next to bash
  - Fix small compat issues
  - Allow using a different OpenSSL binary
  - openssl sha is SHA-0, use dgst command instead

### CODE REVIEW

**Comment by Sp1l** [comment]
Not sure where this is failing in CI... Just tested this in a bash shell and the switching of /bin/sh to /usr/local/bin/sh was OK (FreeBSD 10.2, /bin/sh is bourne shell not bourne again)

**Comment by Sp1l** [comment]
Documented in https://wiki.freebsd.org/BernardSpil/LetsEncrypt and intend to create a port for FreeBSD

**Comment by nylocx** [comment]
I tested your branch and for me it goes into an endless loop with 100% CPU usage.  I'm using zsh on arch linux.

**Comment by bittorf** [comment]
it think the (( ${#} )) thingy is the culprit. but i like your changes overall...

**Comment by lukas2511** [comment]
I think CI also had this problem, it shows a timeout after quite a lot of time. Can't merge it as is, also didn't really look at the changes since it's not working correctly.

**Comment by Sp1l** [comment]
Sorry for the poor quality code :/ Not all my local changes were in.

It now runs but there's an error unrelated to my changes:
```
STDERR:
  + ERROR: An error occurred while sending get-request to https://testca.kurz.pw/directory (Status 502)
```

**Comment by Sp1l** [comment]
Tests are now OK. Any remaining comments?

**Comment by lukas2511** [comment]
I'll still have to look at it, hopefully will get around to it this weekend or early next week.

I don't really like this shell-switchie-thingie, I want this to "just work" in most shells, but I see that at least some of your commits are going in the right direction.

**Comment by lukas2511** [comment]
I really dislike that this contains so much more than just making it compatible with zsh. I'll manually pick out the important parts for now, the rest of the functionality may be added later.

**Comment by lukas2511** [comment]
Initial zsh compatibility is now provided since da2eeda97d04817b895a6c85e72d5c5d53e32241, closing this pullrequest as I don't want that automatic shell selection and some of the other stuff was already fixed.

**Comment by Sp1l** [comment]
Thanks Lukas! Works like a charm now.
Updated the FreeBSD port http://www.freshports.org/security/letsencrypt.sh/
Updated my guide https://wiki.freebsd.org/BernardSpil/LetsEncrypt

**Pull request closed without merging**
