### PR TITLE
help text and initial code for command parameter

### PR DESCRIPTION
**Pull request by germeier**
an initial try for command parameters and help text

RFC

### CODE REVIEW

**Comment by lukas2511** [comment]
yea something like that, structure looks fine to me, but i'd prefer the usage of getopts instead of parsing commandline manually

**Comment by lukas2511** [comment]
would suggest following parameters:

### Modes:

```text
-c (cron operation: default)

-s [domain] (force-sign specific domain)

-r [path/to/cert.pem] (revoke certificate)
```

### Parameters:

```text
-f [path/to/config.sh] (use specific config file)

-k [path/to/privatekey.pem] (use specific private key for given operation, especially useful for certificate revocation)
```

**Comment by germeier** [comment]
OK, I will update this pull request tonight.

What does the "-c" mode should do?

**Comment by lukas2511** [comment]
@germeier 
I'd design the '-c'/cron mode to be basically what the normal operation is right now, but only renewing not signing new certificates.

**Comment by germeier** [comment]
I intend to change this pull request to getopt and after we are all happy with the new structure we can add new features using command line options. I already have a few ideas (e.g. using the software without the need for config files)

**Comment by germeier** [comment]
continues on pull request #35

**Pull request closed without merging**
